=== marshallhuckins/xml-final-project/needsPurchased.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 

<xs:element name="needsPurchased">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        
                        <xs:element name="title">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="author">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="genre" type="xs:string"/>
                        <xs:element name="bookPub" type="xs:string"/>
                        <xs:element name="isbn10">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="isbn13">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                       
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== marshallhuckins/xml-final-project/needsPurchased.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="needsPurchased.xsl"?>
<needsPurchased xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="needsPurchased.xsd">
    <item>
        <title>Harry Potter and the Half-Blood Prince</title>
        <author>J.K. Rowling</author>
        <genre>Fantasy</genre>
        <bookPub>Scholastic Press</bookPub>
        <isbn10>0439784542</isbn10>
        <isbn13>9780439784542</isbn13>
    </item>
    <item>
        <title>Harry Potter and the Deathly Hallows</title>
        <author>J.K. Rowling</author>
        <genre>Fantasy</genre>
        <bookPub>Scholastic Press</bookPub>
        <isbn10>1408855959</isbn10>
        <isbn13>9781408855959</isbn13>
    </item>
</needsPurchased>
